SCORING_SYSTEM = {0: '0', 1: '15', 2: '30', 3: '40'}

POINT = 'POINT'
DEUCE = 'DEUCE'
GAME = 'GAME'
MATCH_COMPLETE = 'MATCH_COMPLETE'
DEUCE_POINTS = 3 #two players are tied 40-40
RESET_GAME_POINTS = 0
TIE_BREAK_SCORE = 6
